# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Docs Publishing

on: [push, pull_request]

# on:
#   push:
#     branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      working_directory: 'docs/'
      
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Install Dependencies
      working-directory: ${{ env.working_directory }}
      run: npm install
      
    - name: Install SSH Client 🔑
      uses: webfactory/ssh-agent@v0.2.0
      with:
        ssh-private-key: ${{ secrets.DEPLOY_KEY }}

    - name: Publish
      working-directory: ${{ env.working_directory }}
      run: GIT_USER=yosiat CURRENT_BRANCH=news-docs USE_SSH=true npm run publish-gh-pages

