name: Panko Serializer CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: [ '2.5', '2.6', '2.7', truffleruby]
        rails: ['4.2.0', '5.2.0', '6.0.0']
        exclude:
          - ruby: 2.7
            rails: 4.2.0

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}

    - name: Install deps
      run: |
        sudo apt update -y
        sudo apt install -y libsqlite3-dev

    - name: Gems Cache
      id: gem-cache
      uses: actions/cache@v1
      with:
       path: vendor/bundle
       key: ${{ runner.os }}-${{ matrix.ruby }}-${{ matrix.rails }}-gem
       restore-keys: |
         ${{ runner.os }}-${{ matrix.ruby }}-${{ matrix.rails }}-gem

    - name: Install gems
      env:
        RAILS_VERSION: ${{ matrix.rails }}
      run: |
        gem install bundler
        bundle config set path 'vendor/bundle'
        bundle check || bundle install --jobs 4 --retry 3

    - name: Compile & test
      env:
        RAILS_VERSION: ${{ matrix.rails }}
      run: |
        bundle exec rake
