name: Ruby

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [ '2.5', '2.6', '2.7.0']
        rails: ['4.2.0', '5.2.0', '6.0.0']
        exclude:
          - ruby: 2.7.0
            rails: 4.2.0

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby ${{ matrix.ruby }}
      uses: actions/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Build and test with Rake
      env:
        RAILS_VERSION: ${{ matrix.rails }}
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec rake
        bundle exec rake benchmarks
